apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data-nfs-pvc
  namespace: minecraft
spec:
  storageClassName: minecraft-data-nfs
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 10Gi
