apiVersion: v1
kind: Service
metadata:
  name: minecraft-forge1-server
  namespace: minecraft
  labels:
    app: minecraft-forge1-server
spec:
#  externalIPs:
#  - 192.168.5.79
  ports:
  - name: mc-tcp
    nodePort: 30565
    port: 25565
    protocol: TCP
    targetPort: 25565
  - name: mc-udp
    nodePort: 30565
    port: 25565
    protocol: UDP
    targetPort: 25565
  selector:
    app: minecraft-forge1-server
  type: LoadBalancer
