apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-data-nfs
  namespace: minecraft
spec:
  storageClassName: minecraft-data-nfs # same storage class as pvc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.5.20 # ip addres of nfs server
    path: "/linuxdata/minecraft-data" # path to directory
