name: docker-build

on:
  push:
    branches: master

jobs:
  multi:
    runs-on: ubuntu-latest
    env: 
      VERSION: 1.16.4 
      FORGE_VERSION: 35.1.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download BuildTools
        uses: suisei-cn/actions-download-file@v1
        id: buildtools  # Remember to give an ID if you need the output
        with:
          url: "https://files.minecraftforge.net/maven/net/minecraftforge/forge/${{env.VERSION}}-${{env.FORGE_VERSION}}/forge-${{env.VERSION}}-${{env.FORGE_VERSION}}-installer.jar"
          target: build/

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jdk

      - run: java -Xmx1024M -jar build/forge-${{env.VERSION}}-${{env.FORGE_VERSION}}-installer.jar --installServer server

      - run: mv server/forge-*.jar server/forge-server.jar

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64, linux/arm/v7
#          platforms: linux/amd64, linux/arm64, linux/arm64/v8, linux/arm/v7, linux/arm/v6, linux/ppc64le
          push: true
          build-args: |
            VERSION=${{env.VERSION}}
          tags: |
            hapewe/forge:latest
            hapewe/forge:${{env.VERSION}}
